// Sample data for the prototype

const TOOLS = [
  {
    id: "claude-code",
    name: "Claude Code",
    initial: "C",
    desc: "Agentic coding tool that lives in your terminal, understands your codebase, and helps you ship faster through natural language commands.",
    homepage: "claude.com/code",
    repo: "github.com/anthropics/claude-code",
    pricing: "Freemium",
    deployment: "Cloud",
    byok: true, api: true,
    tags: ["coding", "cli", "agent", "terminal"],
    upvotes: 4827, favs: 612, comments: 38, reviews: 14,
    addedBy: "ellie.rk", addedAt: "2 days ago",
    featured: true,
  },
  {
    id: "ollama",
    name: "Ollama",
    initial: "O",
    desc: "Get up and running with large language models locally. Bundles model weights, configuration, and data into a single Modelfile.",
    homepage: "ollama.com",
    repo: "github.com/ollama/ollama",
    pricing: "Open Source",
    deployment: "Local",
    byok: false, api: true,
    tags: ["local-llm", "inference", "self-host"],
    upvotes: 3142, favs: 489, comments: 27, reviews: 9,
    addedBy: "mxch",
    addedAt: "5 days ago",
    featured: true,
  },
  {
    id: "cursor",
    name: "Cursor",
    initial: "Ç",
    desc: "The AI code editor. Predicts your next edit, generates code from natural language, and works with your entire codebase.",
    homepage: "cursor.com",
    repo: null,
    pricing: "Freemium",
    deployment: "Cloud",
    byok: true, api: false,
    tags: ["coding", "editor", "ide"],
    upvotes: 2890, favs: 433, comments: 41, reviews: 18,
    addedBy: "dlee", addedAt: "1 week ago",
  },
  {
    id: "perplexity",
    name: "Perplexity",
    initial: "P",
    desc: "Conversational answer engine. Combines a chat-style UI with cited web search to deliver fast, sourced answers to research questions.",
    homepage: "perplexity.ai",
    repo: null,
    pricing: "Freemium",
    deployment: "Cloud",
    byok: false, api: true,
    tags: ["search", "research", "answers"],
    upvotes: 2540, favs: 308, comments: 19, reviews: 11,
    addedBy: "ana.v", addedAt: "1 week ago",
  },
  {
    id: "comfyui",
    name: "ComfyUI",
    initial: "Ç",
    desc: "Most powerful and modular diffusion model GUI and backend. A node-based interface for building complex image-generation pipelines.",
    homepage: "comfy.org",
    repo: "github.com/comfyanonymous/ComfyUI",
    pricing: "Open Source",
    deployment: "Local",
    byok: false, api: false,
    tags: ["image-gen", "diffusion", "node-editor"],
    upvotes: 2104, favs: 367, comments: 22, reviews: 8,
    addedBy: "kestrel", addedAt: "2 weeks ago",
  },
  {
    id: "raycast-ai",
    name: "Raycast AI",
    initial: "R",
    desc: "AI shortcuts and chat baked into your macOS launcher. Summon a quick prompt, write commands, or chat with any frontier model.",
    homepage: "raycast.com/ai",
    repo: null,
    pricing: "Paid",
    deployment: "Hybrid",
    byok: true, api: false,
    tags: ["productivity", "launcher", "macos"],
    upvotes: 1872, favs: 254, comments: 13, reviews: 6,
    addedBy: "noor.k", addedAt: "2 weeks ago",
  },
  {
    id: "llamafile",
    name: "Llamafile",
    initial: "L",
    desc: "Distribute and run LLMs with a single file. Compiles llama.cpp into a portable executable that runs on any major OS.",
    homepage: "llamafile.ai",
    repo: "github.com/Mozilla-Ocho/llamafile",
    pricing: "Open Source",
    deployment: "Local",
    byok: false, api: true,
    tags: ["local-llm", "portable", "cpp"],
    upvotes: 1654, favs: 198, comments: 11, reviews: 5,
    addedBy: "jhowell", addedAt: "3 weeks ago",
  },
  {
    id: "openrouter",
    name: "OpenRouter",
    initial: "Ö",
    desc: "Unified API for 200+ LLMs. Pay-per-token across providers with automatic fallback, prompt caching, and a single key.",
    homepage: "openrouter.ai",
    repo: null,
    pricing: "Paid",
    deployment: "Cloud",
    byok: true, api: true,
    tags: ["llm-router", "api", "billing"],
    upvotes: 1402, favs: 187, comments: 9, reviews: 4,
    addedBy: "tess.w", addedAt: "3 weeks ago",
  },
  {
    id: "lm-studio",
    name: "LM Studio",
    initial: "L",
    desc: "Discover, download, and run local LLMs through a desktop app. Provides a chat interface and an OpenAI-compatible local server.",
    homepage: "lmstudio.ai",
    repo: null,
    pricing: "Free",
    deployment: "Local",
    byok: false, api: true,
    tags: ["local-llm", "desktop", "chat"],
    upvotes: 1287, favs: 165, comments: 8, reviews: 3,
    addedBy: "vik.s", addedAt: "1 month ago",
  },
  {
    id: "v0",
    name: "v0",
    initial: "V",
    desc: "Generative UI from natural language. Describe an interface, get production-ready React + Tailwind code you can copy or deploy.",
    homepage: "v0.app",
    repo: null,
    pricing: "Freemium",
    deployment: "Cloud",
    byok: false, api: false,
    tags: ["ui-gen", "react", "frontend"],
    upvotes: 1142, favs: 144, comments: 14, reviews: 7,
    addedBy: "ellie.rk", addedAt: "1 month ago",
  },
  {
    id: "elevenlabs",
    name: "ElevenLabs",
    initial: "E",
    desc: "Realistic AI voice synthesis and cloning. Generate dialogue, narration, and sound effects in 30+ languages and any voice.",
    homepage: "elevenlabs.io",
    repo: null,
    pricing: "Freemium",
    deployment: "Cloud",
    byok: false, api: true,
    tags: ["voice", "audio", "tts"],
    upvotes: 982, favs: 121, comments: 7, reviews: 4,
    addedBy: "yael.b", addedAt: "1 month ago",
  },
  {
    id: "aider",
    name: "Aider",
    initial: "A",
    desc: "AI pair programming in your terminal. Edits files in your local git repo via natural-language prompts; commits with sensible messages.",
    homepage: "aider.chat",
    repo: "github.com/Aider-AI/aider",
    pricing: "Open Source",
    deployment: "Local",
    byok: true, api: false,
    tags: ["coding", "cli", "git"],
    upvotes: 873, favs: 109, comments: 6, reviews: 4,
    addedBy: "rkumar", addedAt: "2 months ago",
  },
];

const PRICING = ["Open Source", "Freemium", "Paid", "Free"];
const DEPLOYMENT = ["Local", "Cloud", "Hybrid"];
const ACCESS = ["BYOK", "API Available"];
const POPULAR_TAGS = ["coding", "local-llm", "agent", "image-gen", "voice", "search", "ui-gen", "cli", "self-host", "research"];

const COLLECTIONS = [
  { id: "c1", name: "My local stack", desc: "Models and tools I run on my own machine — no cloud bills.", count: 7, isPublic: true, items: ["ollama", "comfyui", "llamafile", "lm-studio"] },
  { id: "c2", name: "Coding agents to try", desc: "Currently evaluating these for daily-driver dev work.", count: 5, isPublic: true, items: ["claude-code", "cursor", "aider"] },
  { id: "c3", name: "Audio + voice", desc: "", count: 3, isPublic: false, items: ["elevenlabs"] },
];

const NOTIFICATIONS = [
  { id: "n1", body: <><strong>m.chen</strong> reviewed <strong>Ollama</strong> — 4 stars</>, meta: "2h", read: false },
  { id: "n2", body: <>Your edit to <strong>Cursor</strong> was approved by @dlee</>, meta: "5h", read: false },
  { id: "n3", body: <>Your tool <strong>SmolBench</strong> got pinned to the homepage</>, meta: "1d", read: false },
  { id: "n4", body: <><strong>ana.v</strong> added <strong>SmolBench</strong> to a collection</>, meta: "2d", read: true },
  { id: "n5", body: <>You earned +12 reputation for a published edit</>, meta: "3d", read: true },
];

const REVIEWS = [
  { author: "mxch", avatar: "M", date: "Mar 12", rating: 5,
    body: "Replaces an entire IDE workflow for me. I throw it at gnarly refactors across 30+ files and it gets ~80% of the way there before I need to step in. The cost is real but worth it for the codebases I work on." },
  { author: "ellie.rk", avatar: "E", date: "Mar 04", rating: 4,
    body: "Lives up to the hype on most tasks. Less great when the context is fuzzy or the codebase is huge and unfamiliar — but for clearly-scoped tickets it's hard to beat. Has become my default for 'I know roughly what I want, just write it'." },
  { author: "rkumar", avatar: "R", date: "Feb 22", rating: 5,
    body: "The terminal-native UX is the whole game. I don't want a chatbot in a tab, I want something that lives where I work. This does that better than anything I've used." },
];

const COMMENTS = [
  { id: 1, author: "tess.w", date: "today", body: "Anyone running this against a private Bedrock endpoint? Curious about the BYOK story for regulated teams.",
    replies: [
      { author: "ellie.rk", date: "today", body: "Yes, works fine — set ANTHROPIC_BASE_URL and the matching auth env var. We've got it pointed at Vertex too." }
    ]
  },
  { id: 2, author: "noor.k", date: "yesterday", body: "Genuinely curious how this compares to Aider for someone already deep in the aider workflow. Worth switching?" },
];

Object.assign(window, { TOOLS, PRICING, DEPLOYMENT, ACCESS, POPULAR_TAGS, COLLECTIONS, NOTIFICATIONS, REVIEWS, COMMENTS });
